language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

branches:
  only:
    - v2

install:
  - yarn install
  - yarn generate

deploy:
  provider: pages
  skip-cleanup: true
  token: $GITHUB_TOKEN
  target-branch: v2-pages
  local-dir: dist
  on:
    branch: v2
